# Generated by Django 3.2.9 on 2021-11-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Titulo')),
                ('Sinopsis', models.TextField(max_length=1200, verbose_name='Sinopsis')),
                ('elenco', models.TextField(max_length=1200, verbose_name='Reparto')),
                ('director', models.CharField(max_length=150, verbose_name='Director')),
                ('calificacion', models.CharField(max_length=150, verbose_name='Calificacion')),
                ('time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Indicar el tiempo en horas')),
                ('soundtrack', models.TextField(max_length=1000, verbose_name='Soundtrack')),
                ('tamanio', models.CharField(max_length=150, verbose_name='Tamaño')),
                ('poster', models.ImageField(null=True, upload_to='posters/peliculas/', verbose_name='Poster de la pelicula')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
