# Generated by Django 3.2.9 on 2021-11-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0002_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=50, verbose_name='Nombre de la pelicula')),
                ('descripcion', models.CharField(max_length=350, verbose_name='Descrpcion resumida')),
                ('clasificacion_edad', models.CharField(choices=[('esp1', 'A'), ('esp2', 'AA'), ('esp3', 'B'), ('esp4', 'B-15'), ('esp5', 'C'), ('esp6', 'R')], max_length=15, verbose_name='Elige la clasificaion')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert', models.TextField(max_length=1000, verbose_name='Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='¿Te gusto la pelicula?')),
            ],
        ),
    ]
