# Generated by Django 3.2.9 on 2021-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0003_categoria_comment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='GGuin',
            field=models.CharField(default=11, max_length=150, verbose_name='Guion'),
            preserve_default=False,
        ),
    ]
