# Generated by Django 3.2.9 on 2021-11-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0004_movie_gguin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='GGuin',
            new_name='beto',
        ),
    ]
