# Generated by Django 3.2.9 on 2021-11-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0005_rename_gguin_movie_beto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='soundtrack',
            field=models.TextField(max_length=1200, verbose_name='Soundtrack'),
        ),
    ]
