# Generated by Django 3.2.9 on 2021-11-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0006_alter_movie_soundtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='soundtrack',
            field=models.TextField(max_length=1750, verbose_name='Soundtrack'),
        ),
    ]
