# Generated by Django 3.2.9 on 2021-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0009_alter_actor_trayectoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='clasificacion_edad',
            field=models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('B', 'B'), ('B-15', 'B-15'), ('C', 'C'), ('R', 'R')], max_length=15, verbose_name='Elige la clasificaion'),
        ),
    ]
