# Generated by Django 3.2.9 on 2021-11-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0012_rename_clasificacaion_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.TextField(default=22, max_length=1000, verbose_name='Añadir respuesta al comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BooleanField(default=False, verbose_name='¿Te gusto el comentario?'),
        ),
    ]
