# Generated by Django 3.2.9 on 2021-11-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0014_auto_20211102_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='comment',
            field=models.TextField(default=22, max_length=1000, verbose_name='Comentario'),
            preserve_default=False,
        ),
    ]
