# Generated by Django 3.2.9 on 2021-11-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0015_score_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=15, verbose_name='Del 1-10 ¿Como calificas la pelicula?'),
        ),
    ]
