# Generated by Django 3.2.9 on 2021-11-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0016_alter_score_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='clasificacion_edad',
            field=models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('B', 'B'), ('B-15', 'B-15'), ('C', 'C'), ('R', 'R'), ('PG-13', 'PG-13')], max_length=15, verbose_name='Elige la clasificacion'),
        ),
    ]
