# Generated by Django 3.2.9 on 2021-11-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0018_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dos', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la pelicula')),
                ('gener', models.BooleanField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspenso', 'Suspense'), ('Terror', 'Terror')], max_length=15, verbose_name='Elegi el genero')),
            ],
        ),
        migrations.AlterField(
            model_name='trailer',
            name='name_movie',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de la pelicula'),
        ),
    ]
