# Generated by Django 3.2.9 on 2021-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0019_auto_20211102_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='gener',
        ),
        migrations.AddField(
            model_name='genero',
            name='genero',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Musical', 'Musical'), ('Suspenso', 'Suspense'), ('Terror', 'Terror')], default=22, max_length=15, verbose_name='Elegi el genero de la pelicula'),
            preserve_default=False,
        ),
    ]
