# Generated by Django 3.2.9 on 2021-11-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0023_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(choices=[('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Musical', 'Musical'), ('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Aventuras', 'Aventuras'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia Romantica', 'Comedia Romantica'), ('Fantasía', 'Fantasía'), ('Comedia Dramatica', 'Comedia Dramatica'), ('Drama', 'Drama')], max_length=20, verbose_name='Elegi el genero de la pelicula'),
        ),
    ]
