# Generated by Django 3.2.9 on 2021-11-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0024_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(choices=[('Comedia Romantica', 'Comedia Romantica'), ('Acción', 'Acción'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Musical', 'Musical'), ('Terror', 'Terror'), ('Fantasía', 'Fantasía'), ('Comedia Dramatica', 'Comedia Dramatica'), ('Drama', 'Drama'), ('Aventuras', 'Aventuras'), ('Comedia', 'Comedia'), ('Suspenso', 'Suspenso')], max_length=20, verbose_name='Elegi el genero de la pelicula'),
        ),
    ]
