# Generated by Django 3.2.9 on 2021-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0025_alter_genero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(choices=[('Terror', 'Terror'), ('Acción', 'Acción'), ('Comedia Romantica', 'Comedia Romantica'), ('Drama', 'Drama'), ('Musical', 'Musical'), ('Aventuras', 'Aventuras'), ('Fantasía', 'Fantasía'), ('Suspenso', 'Suspenso'), ('Comedia', 'Comedia'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia Dramatica', 'Comedia Dramatica')], max_length=20, verbose_name='Elegi el genero de la pelicula'),
        ),
    ]
